import pandas as pd
import matplotlib.pyplot as plt

print("Loading flight data...")
# Read the CSV generated by the C++ engine
df = pd.read_csv("rogue_ap_hunt.csv")

# Create a scatter plot
plt.figure(figsize=(10, 8))
# X axis = Longitude, Y axis = Latitude, Color (c) = RSSI signal strength
scatter = plt.scatter(df['Longitude'], df['Latitude'], c=df['RSSI_dBm'], cmap='jet', s=100, edgecolor='black')

# Add a color bar legend
plt.colorbar(scatter, label='Wi-Fi Signal Strength (RSSI dBm)')

# Formatting the graph
plt.title('Autonomous Drone Network Scan - Rogue AP Heatmap')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.grid(True)

# Save the image
plt.savefig('portfolio_heatmap.png')
print("Success! Heatmap saved as 'portfolio_heatmap.png'")
